### PR TITLE
Cairo support

### PR DESCRIPTION
**Pull request by tschoonj**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tschoonj** [comment]
@awvwgk this PR introduces support for the Cairo plot devices on all platforms.

As I switched to compiling with MSVC on Windows, I ran into trouble keeping fortran support working, as CMake [doesn't like](https://gitlab.kitware.com/cmake/cmake/-/issues/17810) mixing MSVC and gfortran.

Are you particularly attached to Fortran support on Windows, or are you fine dropping it? I personally think that there is value in using the default conda compilers for Windows.

**Comment by awvwgk** [comment]
Fortran support would be essential since plplot is used as dependency in other Fortran projects like the GTK4 Fortran bindings.

**Comment by tschoonj** [comment]
If you are using this PLplot in the Gtk Fortran bindings, why did you never add the Cairo plot devices before? That would allow you to render plots within Gtk windows.

**Comment by awvwgk** [comment]
So far I mainly tested this plplot in CI. Vincent @vmagnin might give more insights on the GTK Fortran requirements on plplot. In any case, having the Fortran bindings is required.

**Comment by tschoonj** [comment]
I have switched back to using the m2w64 compilers. Feel free to merge when CI goes green

**Comment by vmagnin** [comment]
In the gtk-fortran project, we use the "extcairo" PLplot driver:
```fortran
call plsdev("extcairo")
```

**Comment by tschoonj** [comment]
> In the gtk-fortran project, we use the "extcairo" (Cairo External Context Driver) PLplot driver for rendering in a GTK window:
> 
> ```fortran
> call plsdev("extcairo")
> ```

Thanks, just as I expected. This PR when merged in will ensure that you can also do that with the conda build of PLplot

**Comment by tschoonj** [comment]
@awvwgk Got it working now, with `clang` used for the C and C++ code, and `gfortran` for the fortran bindings.

**Pull request merged**
